FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o gateway .

FROM alpine:latest

WORKDIR /app/

COPY --from=builder /app/gateway .

RUN mkdir -p ./setting
COPY setting/setting.json ./setting

RUN mkdir -p userManager
COPY userManager/user.json ./userManager

CMD ["./gateway"]