FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o chatbot .

FROM alpine:latest

WORKDIR /app/

COPY --from=builder /app/chatbot .

RUN mkdir -p ./setting
COPY setting/setting.json ./setting

CMD ["./chatbot"]